"""empty message

Revision ID: 6d224929f65a
Revises: 
Create Date: 2025-10-01 03:44:30.379865

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6d224929f65a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hero',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('localized_name', sa.String(length=100), nullable=False),
    sa.Column('primary_attr', sa.Enum('STRENGTH', 'AGILITY', 'INTELLIGENCE', 'UNIVERSAL', name='dota2_hero_attributes_enum'), nullable=False),
    sa.Column('faction', sa.Enum('RADIANT', 'DIRE', 'NONE', name='dota2_hero_factions_enum'), nullable=False),
    sa.Column('attack_type', sa.String(length=10), nullable=False),
    sa.Column('roles', sa.JSON(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('updated', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_hero'))
    )
    op.create_table('media',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('file_path', sa.String(length=255), nullable=False),
    sa.Column('file_type', sa.String(length=50), nullable=False),
    sa.Column('resolution', sa.String(), nullable=False),
    sa.Column('width', sa.Integer(), nullable=False),
    sa.Column('height', sa.Integer(), nullable=False),
    sa.Column('file_size_kb', sa.Float(), nullable=False),
    sa.Column('mode', sa.String(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('updated', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_media'))
    )
    op.create_table('user_account',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('fullname', sa.String(length=120), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('updated', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_account')),
    sa.UniqueConstraint('email', name=op.f('uq_user_account_email')),
    sa.UniqueConstraint('username', name=op.f('uq_user_account_username'))
    )
    op.create_table('account',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bio', sa.String(length=500), nullable=True),
    sa.Column('country', sa.Enum('USA', 'CHINA', 'RUSSIA', 'SPAIN', 'PORTUGAL', 'FRANCE', 'GERMANY', 'JAPAN', 'IRAN', 'CANADA', 'UNITED_KINGDOM', 'AUSTRALIA', 'BRAZIL', 'INDIA', 'SOUTH_KOREA', 'TURKEY', 'ITALY', 'POLAND', 'UKRAINE', 'THAILAND', 'VIETNAM', 'INDONESIA', 'CZECH_REPUBLIC', 'ROMANIA', 'HUNGARY', 'BULGARIA', 'GREECE', 'NETHERLANDS', 'SWEDEN', 'FINLAND', 'NORWAY', 'DENMARK', 'SLOVAKIA', 'SERBIA', 'CROATIA', 'PHILIPPINES', 'MALAYSIA', 'SINGAPORE', 'SOUTH_AFRICA', 'NEW_ZEALAND', 'MEXICO', 'ARGENTINA', 'CHILE', 'PERU', 'COLOMBIA', 'SAUDI_ARABIA', 'UNITED_ARAB_EMIRATES', 'EGYPT', 'MOROCCO', 'NIGERIA', 'KENYA', name='countryenum'), nullable=True),
    sa.Column('custom_url', sa.String(length=100), nullable=True),
    sa.Column('phonenumber', sa.String(length=20), nullable=True),
    sa.Column('real_name', sa.String(length=100), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('avatar_id', sa.Integer(), nullable=True),
    sa.Column('language', sa.Enum('ENGLISH', 'CHINESE', 'RUSSIAN', 'SPANISH', 'PORTUGUESE', 'FRENCH', 'GERMAN', 'JAPANESE', 'PERSIAN', name='languageenum'), nullable=False),
    sa.Column('birth_date', sa.DateTime(), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('updated', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['avatar_id'], ['media.id'], name=op.f('fk_account_avatar_id_media')),
    sa.ForeignKeyConstraint(['user_id'], ['user_account.id'], name=op.f('fk_account_user_id_user_account')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_account')),
    sa.UniqueConstraint('custom_url', name=op.f('uq_account_custom_url'))
    )
    op.create_table('follow',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('follower_id', sa.Integer(), nullable=False),
    sa.Column('followed_id', sa.Integer(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('updated', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['followed_id'], ['user_account.id'], name=op.f('fk_follow_followed_id_user_account')),
    sa.ForeignKeyConstraint(['followed_id'], ['user_account.id'], name=op.f('fk_follow_followed_id_user_account')),
    sa.ForeignKeyConstraint(['follower_id'], ['user_account.id'], name=op.f('fk_follow_follower_id_user_account')),
    sa.ForeignKeyConstraint(['follower_id'], ['user_account.id'], name=op.f('fk_follow_follower_id_user_account')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_follow')),
    sa.UniqueConstraint('follower_id', 'followed_id', name='unique_follow')
    )
    op.create_table('hero_connections',
    sa.Column('hero_id', sa.Integer(), nullable=False),
    sa.Column('connected_hero_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['connected_hero_id'], ['hero.id'], name=op.f('fk_hero_connections_connected_hero_id_hero')),
    sa.ForeignKeyConstraint(['hero_id'], ['hero.id'], name=op.f('fk_hero_connections_hero_id_hero')),
    sa.PrimaryKeyConstraint('hero_id', 'connected_hero_id', name=op.f('pk_hero_connections'))
    )
    op.create_table('revoked_token',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('jti', sa.String(length=120), nullable=False),
    sa.Column('ttype', sa.String(length=30), nullable=False),
    sa.Column('reason', sa.String(length=255), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('updated', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user_account.id'], name=op.f('fk_revoked_token_user_id_user_account')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_revoked_token')),
    sa.UniqueConstraint('jti', name=op.f('uq_revoked_token_jti'))
    )
    op.create_table('story',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('content', sa.String(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('updated', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user_account.id'], name=op.f('fk_story_user_id_user_account')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_story')),
    sa.UniqueConstraint('slug', name=op.f('uq_story_slug'))
    )
    op.create_table('user_password',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('hashed_password', sa.String(length=128), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('updated', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user_account.id'], name=op.f('fk_user_password_user_id_user_account')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_password'))
    )
    op.create_table('comment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('content', sa.String(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('story_id', sa.Integer(), nullable=True),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('updated', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['comment.id'], name=op.f('fk_comment_parent_id_comment')),
    sa.ForeignKeyConstraint(['story_id'], ['story.id'], name=op.f('fk_comment_story_id_story')),
    sa.ForeignKeyConstraint(['user_id'], ['user_account.id'], name=op.f('fk_comment_user_id_user_account')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_comment'))
    )
    op.create_table('profile',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('updated', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['account.id'], name=op.f('fk_profile_account_id_account')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_profile')),
    sa.UniqueConstraint('account_id', name=op.f('uq_profile_account_id'))
    )
    op.create_table('favorite_heroes',
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.Column('hero_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['hero_id'], ['hero.id'], name=op.f('fk_favorite_heroes_hero_id_hero')),
    sa.ForeignKeyConstraint(['profile_id'], ['profile.id'], name=op.f('fk_favorite_heroes_profile_id_profile')),
    sa.PrimaryKeyConstraint('profile_id', 'hero_id', name=op.f('pk_favorite_heroes'))
    )
    op.create_table('favorite_stories',
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.Column('story_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['profile.id'], name=op.f('fk_favorite_stories_profile_id_profile')),
    sa.ForeignKeyConstraint(['story_id'], ['story.id'], name=op.f('fk_favorite_stories_story_id_story')),
    sa.PrimaryKeyConstraint('profile_id', 'story_id', name=op.f('pk_favorite_stories'))
    )
    op.create_table('like',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('story_id', sa.Integer(), nullable=True),
    sa.Column('comment_id', sa.Integer(), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('updated', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['comment_id'], ['comment.id'], name=op.f('fk_like_comment_id_comment')),
    sa.ForeignKeyConstraint(['story_id'], ['story.id'], name=op.f('fk_like_story_id_story')),
    sa.ForeignKeyConstraint(['user_id'], ['user_account.id'], name=op.f('fk_like_user_id_user_account')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_like'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('like')
    op.drop_table('favorite_stories')
    op.drop_table('favorite_heroes')
    op.drop_table('profile')
    op.drop_table('comment')
    op.drop_table('user_password')
    op.drop_table('story')
    op.drop_table('revoked_token')
    op.drop_table('hero_connections')
    op.drop_table('follow')
    op.drop_table('account')
    op.drop_table('user_account')
    op.drop_table('media')
    op.drop_table('hero')
    # ### end Alembic commands ###
